title_primary: "朝花夕拾" # the bigger text
title_secondary: "Mdreame" # the smaller text
keywords:

truncate_len: 160

twitter: #username
rss: atom.xml
weibo: #username/id
instagram: #username
github: #username

# Choose the comment service according to your need.
# Please do not use the two services at the same time.
livere: # [data-uid] on livere.com
disqus: blog-mdreame-space # [short_name] on disqus.com
dove: # For fun ONLY. Set to true to 'disable' comments on your site.

# Set true to show the page indicator.
showPageCount: true

# Set true to show category or tags behind post titles
showCategories: true
showTags: true

# Color scheme
themeStyle: light # light/dark

