title_primary: "朝花夕拾" # the bigger text
title_secondary: "Mdreame" # the smaller text
keywords:

truncate_len: 120

twitter: #username
rss: atom.xml
weibo: #username/id
instagram: #username
github: #username
email: mdreame@qq.com

# Choose the comment service according to your need.
# Please do not use the two services at the same time.
livere: # [data-uid] on livere.com
disqus: blog-mdreame-space # [short_name] on disqus.com
dove: # For fun ONLY. Set to true to 'disable' comments on your site.

# Set true to show the page indicator.
showPageCount: true

# Set true to show category or tags behind post titles
showCategories: false
showTags: true

# Color scheme
themeStyle: light # light/dark

# giscus:
#   enable: true
#   repo: Mdreame/joplin-blog-comment # Github repository name
#   repo_id: R_kgDOQ_JqyA # Github repository id
#   category: Announcements # Github discussion category
#   category_id: DIC_kwDOQ_JqyM4C1SiL # Github discussion category id
#   # Available values: pathname | url | title | og:title
#   mapping: pathname
#   # Available values: 0 | 1 
#   reactions_enabled: 1
#    # Available values: 0 | 1 
#   emit_metadata: 1
#   # Available values: light | dark | dark_high_contrast | transparent_dark | preferred-color-scheme
#   theme: light
#   # Available values: en | zh-C
#   lang: zh-CN
#   # Available value: anonymous
#   crossorigin: anonymous